### ISSUE TITLE
Request permissions on runtime

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#128]
https://developer.android.com/training/permissions/requesting.html

For API 23 or greater, we should request permissions as they are needed. The app is crashing on the region select page because we're not (I think). So we need to request permission for location (just on this page?). 

If the permission is denied, should the app close? It seems like everyone should approve that permission. And after that, if they have location services turned off, then the app will still work, though any location-based features will not.

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.pbm, PID: 2665
                  java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
                      at android.os.Parcel.readException(Parcel.java:1599)
                      at android.os.Parcel.readException(Parcel.java:1552)
                      at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
                      at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
                      at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
                      at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                      at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                      at com.google.android.gms.internal.zzqc$zza.zzb(Unknown Source)
                      at com.google.android.gms.internal.zzqm.zzf(Unknown Source)
                      at com.google.android.gms.internal.zzqm.zzd(Unknown Source)
                      at com.google.android.gms.internal.zzqr.zzd(Unknown Source)
                      at com.google.android.gms.internal.zzqp.zzd(Unknown Source)
                      at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
                      at com.pbm.PinballMapActivity.onConnected(PinballMapActivity.java:386)
                      at com.google.android.gms.common.internal.zzm.zzp(Unknown Source)
                      at com.google.android.gms.internal.zzqp.zzn(Unknown Source)
                      at com.google.android.gms.internal.zzqn.zzarm(Unknown Source)
                      at com.google.android.gms.internal.zzqn.onConnected(Unknown Source)
                      at com.google.android.gms.internal.zzqr.onConnected(Unknown Source)
                      at com.google.android.gms.internal.zzqf.onConnected(Unknown Source)
                      at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
                      at com.google.android.gms.common.internal.zze$zzj.zzaua(Unknown Source)
                      at com.google.android.gms.common.internal.zze$zza.zzc(Unknown Source)
                      at com.google.android.gms.common.internal.zze$zza.zzv(Unknown Source)
                      at com.google.android.gms.common.internal.zze$zze.zzauc(Unknown Source)
                      at com.google.android.gms.common.internal.zze$zzd.handleMessage(Unknown Source)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by RyanTG** [comment]
This line (and the line below) are giving a warning: https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/PinballMapActivity.java#L385

If I let Android Studio resolve it, it adds this:

        if (ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            // TODO: Consider calling
            //    ActivityCompat#requestPermissions
            // here to request the missing permissions, and then overriding
            //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
            //                                          int[] grantResults)
            // to handle the case where the user grants the permission. See the documentation
            // for ActivityCompat#requestPermissions for more details.
            
            return;
        }

This fixes the crashing, but doesn't actually request location (because that part isn't in there yet!). But I can't figure out how to add it correctly. I'm following the developer page, and also this (http://stackoverflow.com/questions/33406762/access-fine-location-securityexception-despite-specifying-the-permission-in-the), and am basically adding: 
    ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSION_REQUEST_ACCESS_FINE_LOCATION);

But the problem is that "PERMISSION_REQUEST_ACCESS_FINE_LOCATION" is undefined, and I don't know where to define it. So I'm stuck. Almost had it!
