### ISSUE TITLE
Squash bugs before Auth release

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#136]
I'm stuck on trying to fix some bugs. I think I've hit the limits of my capabilities, and we need some expert brains on this before we release it. 

One thing that may be important: I was fairly gung ho about changing to SDK version to 24, and updating some dependencies. Since I updated those, there are now new versions available (25, and play services 9.8). When I upgrade to those newest ones, more bugs come up (in api 25, it can't find location). So I'm not going to update them anymore (aka I reverted it, so we're still at 24). However, I wonder if I brought it to 24 without adequately accounting for everything.

Here are the bugs I'm getting:

- On my device (OnePlus X, using API 24), with the app downloaded through the play store, the app crashes when I do any sort of lookup. Error:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference
	at com.pbm.p.onCreateOptionsMenu(Unknown Source)
	at com.pbm.LocationLookupDetail.onCreateOptionsMenu(Unknown Source)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
	at android.support.v4.app.o.onCreatePanelMenu(Unknown Source)
	at android.support.v7.view.i.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.g$a.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.l.b(Unknown Source)
	at android.support.v7.app.l.f(Unknown Source)
	at android.support.v7.app.l$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

If you go to Profile, and then click on a location that that user has edited, then you can see the location detail for a location (just noting this, because at first I wondered if the error was somehow due to the No Data bug - but it's not).

- With API 25, in the emulator, I get this error when I do a location lookup:

    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 598240 bytes

**Comment by scottwainstock** [comment]
Click the map button on a page with >1 locations:

java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.pbm.Location[]
                                                           at com.pbm.DisplayOnMap.onMapReady(DisplayOnMap.java:52)
                                                           at com.google.android.gms.maps.MapFragment$zza$1.zza(Unknown Source)
                                                           at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
                                                           at android.os.Binder.transact(Binder.java:387)
                                                           at yd.a(:com.google.android.gms.DynamiteModulesB:82)
                                                           at maps.ad.t$5.run(Unknown Source)
                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:148)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by RyanTG** [comment]
You can access the lookup results view (so you can click a map button for multiple locations)? I can't get that far on the beta.

**Comment by scottwainstock** [comment]
I fixed that issue. Commits/new beta coming tonight. I'm just looking at the API 25 thing right now.

Here was the "java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference" issue:
http://stackoverflow.com/a/23840049

I had to add proguard to get the app to compile (we've added a lot of 3rd party libraries and were getting a "too many methods" error). So, it's super unlikely this would have been on your mind during debugging.

**Comment by RyanTG** [comment]
This Thanksgiving, I'm thankful for you squashing bugs.

I saw something about proguard in an SO answer... But it just felt to like too much for me. Glad you found the answer!

**Comment by scottwainstock** [comment]
The API 25 issue seems huge:
http://stackoverflow.com/questions/39507250/why-does-android-n-throw-transactiontoolargeexception-when-using-bundles

I don't have a fix for it right now, and it sounds like it's going to be a lot of work.

I'll send an updated beta that fixes the other two issues.

**Comment by RyanTG** [comment]
Sweet! Working great on my phone. Thanks for the fixes. I was worried that I had introduced problems.

I'll check on this some more: I had to quit the app multiple times before it actually quit.

Now I need to take the "map of nearby" screenshot when I'm not at someone's home.

**Comment by RyanTG** [comment]
I installed Android 7.1 on my phone (nougat). This is the only crash I've experienced so far:

java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.distanceTo(android.location.Location)' on a null object reference
	at com.pbm.e.a(Unknown Source)
	at com.pbm.Profile.d(Unknown Source)
	at com.pbm.Profile$2.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)

It occurred when I viewed the Profile. And it occurred because: I allowed the app access to my Location, it didn't find it! The locations had no distance listed. In the past when similar things have happened, I've found that I can get it to find my location by opening the profile. But this time the app crashed. HOWEVER, when I reopened it, it had my location.

So I think there's something happening with that initial location request, where it gets access to the location but doesn't actually find it.

**Comment by scottwainstock** [comment]
I'm a little confused... this is that build that's dying in the emulator
with the "you sent too much data" error?

**Comment by RyanTG** [comment]
Yes, this is the latest beta build. I installed it from the play store. I haven't experienced the too much data error yet.

**Comment by RyanTG** [comment]
Is this a beta thing? ALL of the locations are saying they were last updated today.

**Comment by RyanTG** [comment]
Finally got the "TransactionTooLargeException" error on my phone, using Android N. It didn't occur until after I switched from the beta to a version that I pushed to my phone from AS (though that doesn't necessary mean I wouldn't have gotten it while in the beta). Then I fooled around for a bit and got it.

From that fooling around, I've found that I can't produce that crash in the LA region, but I can in Portland. So, my assumption is that it has something to do with the quantity of locations that are loaded when you click "lookup by location". If that's the case, then a possible solution may be to limit the amount of results until you scroll to the bottom of the list. Like, load 25, scroll down, load 25 more...?

**Comment by scottwainstock** [comment]
Sounds likely, yeah... thanks for the analysis... this feels like an actual
path forward.

**Comment by RyanTG** [comment]
After more testing: 

In Los Angeles, it does crash, but only on the Lookup by Operator view (there are only like five operators listed, but it still crashes on that view).

In Portland, it seems to crash on ALL of the lookups.

**Comment by RyanTG** [comment]
App is crashing, but I think it's for a different reason. Can't tell if this error is something specific to my phone. I was using the app just fine in the Los Angeles region. Then I switched to Portland and got this. Now it happens every time it starts up (note: I haven't reinstalled the app yet). 

I'm using Android M.

D/AppTracker: App Event: stop
E/AndroidRuntime: FATAL EXCEPTION: Thread-1506
                  Process: com.pbm, PID: 25956
                  java.lang.NumberFormatException: Invalid long: "null"
                      at java.lang.Long.invalidLong(Long.java:124)
                      at java.lang.Long.parse(Long.java:363)
                      at java.lang.Long.parseLong(Long.java:353)
                      at java.lang.Long.parseLong(Long.java:321)
                      at com.pbm.PBMApplication.initializeMachineScores(PBMApplication.java:442)
                      at com.pbm.PBMApplication.initializeData(PBMApplication.java:398)
                      at com.pbm.InitializingScreen$SplashThread.run(InitializingScreen.java:38)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
D/AppTracker: App Event: crash
E/AbstractTracker: mTrackerAsyncQueryHandler is null
E/ActivityThread: Failed to find provider info for net.oneplus.odm.provider.PayloadProvider
E/AbstractTracker: Unknown URL content://net.oneplus.odm.provider.PayloadProvider/OP_payload_upload_table

**Comment by RyanTG** [comment]
There's also an error when I change regions. Right when I click "change region" and it sends me back to the login page (this is when I am using the app as a guest), I get this error. But the app doesn't crash. I can't tell if there are any negative consequences.

D/AppTracker: App Event: start
E/ActivityThread: Failed to find provider info for net.oneplus.odm.provider.PayloadProvider
E/AbstractTracker: Unknown URL content://net.oneplus.odm.provider.PayloadProvider/OP_payload_upload_table
E/WindowManager: android.view.WindowLeaked: Activity com.pbm.PBMMenu has leaked window android.widget.PopupWindow$PopupDecorView{3a88c36 V.E...... .......D 0,0-539,1188} that was originally added here
                     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:375)
                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                     at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
                     at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
                     at android.support.v7.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:102)
                     at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
                     at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:129)
                     at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:206)
                     at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:715)
                     at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:160)
                     at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187)
                     at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:286)
                     at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:171)
                     at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:803)
                     at android.os.Handler.handleCallback(Handler.java:739)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:148)
                     at android.app.ActivityThread.main(ActivityThread.java:5539)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
D/OpenGLRenderer: endAllStagingAnimators on 0x9df88200 (MenuPopupWindow$MenuDropDownListView) with handle 0x9e01b880
D/AppTracker: App Event: stop

**Comment by RyanTG** [comment]
I think this error when changing regions:
`E/WindowManager: android.view.WindowLeaked: Activity com.pbm.PBMMenu has leaked window android.widget.PopupWindow$PopupDecorView{3a88c36 V.E...... .......D 0,0-539,1188} that was originally added here`
is resolved with https://github.com/scottwainstock/pbm-android/pull/143/commits/cf992b6f019c765abf4f187d89273d72d1cebe5d

Perhaps there's another way to do it. But that's all I could figure out.

**Comment by RyanTG** [comment]
Woohoo! Resolved this error: https://github.com/scottwainstock/pbm-android/issues/136#issuecomment-276276293

So, `java.lang.NumberFormatException: Invalid long: "null"` was occurring when loading Portland because the region contained a few - scores. Like, scores with no value. I think these were entered by @scottwainstock recently.

Example: Marie's Lounge's Dirty Harry: by Unknown on Sat, 28 Jan 2017 00:54:08 +0000

Even though it says Unknown, sswtest was adding scores to the same machine around this same time (testing the quintillion point score). So these blank scores seem to be a result of your testing.

But now that's fixed, right? I think people won't be able to enter blank scores. When I enter a blank score in the Android app, it says "Thanks for updating that machine." but nothing is added (note, it should probably give an error, AND valid scores should probably say "Thanks for entering that score." But that's another issue...

Anyway, as long as no one can ever enter a blank score, then we're fine. Otherwise, it will crash the app.

**Comment by RyanTG** [comment]
Regarding the TransactionTooLargeException, can that be "resolved" by switching to sdk 23 and target 23? Like, would N devices be ok then?

Another hack would be to remove onSaveInstanceState in places where it won't totally suck to remove it. But that's probably a bad idea.

this thread goes on for a while, with various ideas https://code.google.com/p/android/issues/detail?id=212316

https://medium.com/@andrei.rosca/android-7-transactiontoolargeexception-a-workaround-ffb60fd18bef#.fni9yojah

**Comment by RyanTG** [comment]
I tested it. I changed to sdk 23, and it's not crashing when using a 25 device. The log still shows an error (pasted below), but it doesn't cause the app to crash. In my initial testing on 23 and 25 devices, the only issue is on the region select screen. It's not showing the little header that says, "Alphabetical | Closest" or whatever it says. That part is missing. I'll investigate. 

E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 676016)
E/ActivityThread: App sent too much data in instance state, so it was ignored
                  android.os.TransactionTooLargeException: data parcel size 676016 bytes
                      at android.os.BinderProxy.transactNative(Native Method)
                      at android.os.BinderProxy.transact(Binder.java:615)
                      at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
                      at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3773)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

What say you?

**Comment by RyanTG** [comment]
Spent a while trying to figure out that region select pager issue. I failed. By all indication (library versions and such) it should work. I think I give up.

I don't know if downgrading is the best idea. But I wish that large transaction error didn't suck so much.

**Comment by scottwainstock** [comment]
@RyanTG What did we get when we upgraded? If we "downgrade", don't people with the newer SDK just have this issue anyway? Can we FORCE a version of the sdk?

**Comment by RyanTG** [comment]
People with the newer SDK don't experience the error. It's just a warning that they don't see.

I don't know exactly what we got from upgrading, aside from an updated way for requesting permissions (prompts you when the permission is needed).

Note that downgrading involves removing a bunch of "if API 25" statements in the code. It's tedious, and I can do it in a new fork if you want to check it out.

On February 4, 2017 3:15:46 PM PST, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG What did we get when we upgraded? If we "downgrade", don't
>people with the newer SDK just have this issue anyway? Can we FORCE a
>version of the sdk?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm-android/issues/136#issuecomment-277485230

-- 
Sent while mobile.

**Comment by RyanTG** [comment]
We are using 22 in the live app, I believe. I think I took advantage of some 23 library.

When I downgraded to 23 the other day, I had a problem with the region select pager. It's a known issue, but it was resolved in the build I was using, so I didn't understand why I was seeing it. I gave up and reset my branch after that..

**Comment by RyanTG** [comment]
What say you? Do you want me to make a branch for SDK 23?

**Comment by scottwainstock** [comment]
@RyanTG Up to you. I haven't had a chance to really dig into fixing any Android stuff since I've been so busy with iOS. So, I have no idea what's the easiest path forward here.

**Comment by scottwainstock** [comment]
https://code.google.com/p/android/issues/detail?id=183127
https://developer.android.com/topic/libraries/support-library/rev-archive.html

**Comment by RyanTG** [comment]
Looking back at this commit https://github.com/scottwainstock/pbm-android/commit/e54c4adb74d67d6a317ea0295eebf0db0f54d689

It looks like that "cardview" library works in api 22. So now the answer to "what did we get from upgrading?" is "I don't know - perhaps nothing."

**Comment by RyanTG** [comment]
I edited the above comment. We are using some 23 things - button widgets.

**Comment by RyanTG** [comment]
Possible solution for the pager: http://stackoverflow.com/a/32379051
Basically, insert old v22 pager files into the project.

**Comment by RyanTG** [comment]
http://stackoverflow.com/a/32379051 did not work. Buncha dumb errors.

**Comment by scottwainstock** [comment]
This is the downgrade from 24 to 23.
https://github.com/scottwainstock/pbm-android/commit/a882ef6776818076ad6dbfe22bdab68f3f99a58f

This is the fix for the region tabs.
https://github.com/scottwainstock/pbm-android/commit/239125168e519f80f5db172e7137deed27cd579d

**Comment by scottwainstock** [comment]
@RyanTG I just pushed a new build to the developer panel... I think you should get it automatically, but let me know if that doesn't happen. It's version 27.

**Comment by RyanTG** [comment]
Sweet!!!

I just swapped my phone's rom the other day and hadn't added back all apps, so I didn't even have this installed (plus, previously I was just using the version that I sent from android studio). I reinstalled it right now. Can't immediately tell if I have version 27. But if not, I'm sure the update will come soon.

**Comment by RyanTG** [comment]
App last updated on Nov 24. Play store is lagging with the update.

**Comment by RyanTG** [comment]
Since my phone doesn't use API 24, I'll verify that it doesn't crash (even though I already know it won't) with Android studio.

Cool that tablayout worked on the region select page. I'm going to try and change the color of the text because right now it's white text and blue background.

**Comment by RyanTG** [comment]
updated colors on region select screen: https://github.com/scottwainstock/pbm-android/pull/144/commits/936261aec130bddb2135310eacb35f348b5622e3

API 23 seems good. Closing this. If we find more bugs we can make new issues.
