### ISSUE TITLE
If the region you're on gets deleted, the app crashes

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#146]
Steps:
Open Android app to a region that I'm about to delete.
Close Android app.
Delete region.
Open Android app.

Result:
App crashes. Have to reinstall to get past it.

I think we need something similar to the iOS app, where the app checks if the current region exists, and if it doesn't, you get sent to the region select screen.

**Comment by RyanTG** [comment]
Oh wait, this doesn't have to be auth. We're not going to delete/copy any regions until after.

But, we'd have to release an app update after this is added.

**Comment by RyanTG** [comment]
I deleted a region while connected to ADB, so I could deliver the error message:

````
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.pbm, PID: 3436
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pbm/com.pbm.SplashScreen}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.pbm.Region.name' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.pbm.Region.name' on a null object reference
                      at com.pbm.SplashScreen.onCreate(SplashScreen.java:53)
                      at android.app.Activity.performCreate(Activity.java:6237)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
I/Process: Sending signal. PID: 3436 SIG: 9
Disconnected from the target VM, address: 'localhost:8615', transport: 'socket'
````

Before seeing this, my assumption had been to add some "if region name is null" thing to SplashScreen.java. And yeah, that seems right. Or something close to that.

**Comment by RyanTG** [comment]
Argh, I can't slay this. As it is right now, it loses it on https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/SplashScreen.java#L53 `region.name`.

So it seems logical to say: if region.name is NOT null, then load the region; else load the region select screen. But `if (region.name != null && !region.name.equals("")) {` still produces a nullpointerexception. I don't get it. I've tried a number of things.

````
		} else if (prefRegion != -1) {
			Region region = app.getRegion(prefRegion);
			if (region.name != null && !region.name.equals("")) {
				setRegionBase(httpBase + apiPath + "region/" + region.name + "/");
				Intent myIntent = new Intent();
				myIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
				myIntent.setClassName("com.pbm", "com.pbm.InitializingScreen");
				startActivityForResult(myIntent, PinballMapActivity.QUIT_RESULT);
			} else {
				Intent loginIntent = new Intent();
				loginIntent.setClassName("com.pbm", "com.pbm.Login");
				startActivityForResult(loginIntent, PinballMapActivity.QUIT_RESULT);
			}
````

**Comment by RyanTG** [comment]
Notes to self throughout the day:

When you reopen the app, [splash screen](https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/SplashScreen.java) loads and then sends you to your last region (prefRegion). If that region has been deleted, then the string region.name is null. App crashes.

Left off at https://github.com/scottwainstock/pbm-android/issues/146#issuecomment-280255637

To REALLY see the value of the region.name string, print it before the crash (is it null or is it "null"?):

- uh that is more confusing than I expected, because it should be like:
private static final String TAG = "myApp";
Log.d(TAG, "did something" + region.name);

And I'm not sure where to put that tag.

Anyway, perhaps on https://github.com/scottwainstock/pbm-android/blob/master/app/src/main/java/com/pbm/Region.java say something like: IF name = null, then string name = "jeff"

**Comment by RyanTG** [comment]
Maybe Region.java is not the right file to work with. Nothing I do on it seems to affect splashscreen.

**Comment by scottwainstock** [comment]
@RyanTG Region.java is just the model for region. It's supposed to tell you things about the region, not drive functionality after what it tells you.

**Comment by RyanTG** [comment]
@scottwainstock So when you launch the app that model is used to tell you about the last region you were using, right? So if that region has been deleted the values will all be null?

**Comment by RyanTG** [comment]
Ah, I think I may have to instead check for null prior to `Region region = app.getRegion(prefRegion);`

Like, `if (app.getRegion(prefRegion) == null` or something.

My house keeps losing power, though :<

**Comment by RyanTG** [comment]
Sh'doit: https://github.com/scottwainstock/pbm-android/pull/147/commits/f0374943597f42222244d2feaf1ec46ac1c1f4ba

**Comment by RyanTG** [comment]
I'll take your silence as agreement.
