### ISSUE TITLE
Donate button is crashing app

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#171]

**Comment by RyanTG** [comment]
````
11-29 18:06:18.442 1706-3075/? E/ActivityManager: Activity Manager Crash
                                                  java.lang.IllegalArgumentException: Unknown component: com.android.browser/com.android.browser.BrowserActivity
                                                      at com.android.server.pm.PackageManagerService.isComponentProtected(PackageManagerService.java:21035)
                                                      at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:800)
                                                      at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4543)
                                                      at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4511)
                                                      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:165)
                                                      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2977)
                                                      at android.os.Binder.execTransact(Binder.java:565)
11-29 18:06:18.443 3458-3458/com.pbm D/AndroidRuntime: Shutting down VM
11-29 18:06:18.445 3458-3458/com.pbm E/AndroidRuntime: FATAL EXCEPTION: main
                                                       Process: com.pbm, PID: 3458
                                                       java.lang.IllegalArgumentException: Unknown component: com.android.browser/com.android.browser.BrowserActivity
                                                           at android.os.Parcel.readException(Parcel.java:1688)
                                                           at android.os.Parcel.readException(Parcel.java:1637)
                                                           at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3101)
                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
                                                           at android.app.Activity.startActivityForResult(Activity.java:4229)
                                                           at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                           at android.app.Activity.startActivityForResult(Activity.java:4187)
                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                           at android.app.Activity.startActivity(Activity.java:4526)
                                                           at android.app.Activity.startActivity(Activity.java:4494)
                                                           at com.pbm.Donate$1.onClick(Donate.java:48)
                                                           at android.view.View.performClick(View.java:5637)
                                                           at android.view.View$PerformClick.run(View.java:22433)
                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-29 18:06:18.450 1706-4707/? W/ActivityManager:   Force finishing activity com.pbm/.Donate
11-29 18:06:18.455
````

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/bdb5bf9002f4ddefd1f62f1468a00d3b258e3462
