### ISSUE TITLE
App crashes when you switch to a different app

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#175]
I need to verify this a few more times. But if I switch to another app, without quitting pbm, it will crash.

````
12-08 22:44:28.216 9126-9126/com.pbm E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.pbm, PID: 9126
        android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7fe60e3 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.widget.Toast$TN.handleShow(Toast.java:459)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)````

**Comment by RyanTG** [comment]
Not currently able to replicate this. But previously I'd seen it a few times.

So: hold on this for now until I get more info/close it.

**Comment by RyanTG** [comment]
Can't replicate. Closing.
