### ISSUE TITLE
Recently Added - crashing if visited before rest of data loads

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm-android#183]
From what I can tell: 

- open app
- immediately visit recently added section

Result: crash.

If you wait and load the rest of the data (like if you visit the lookup by location section and wait for the data to load) before visiting recently added, then it doesn't crash. I replicated out a couple times.

**Comment by scottwainstock** [comment]
@RyanTG Crash log would be helpful, I'm not able to replicate it on hardware.

**Comment by RyanTG** [comment]
Log

````
01-03 20:32:26.257 12935-12935/? D/com.pbm: initializing data
01-03 20:32:26.340 12935-12935/? D/com.pbm: TIMING STARTING REGION
01-03 20:32:27.683 12935-12982/? D/com.pbm: https://pinballmap.com/api/v1/regions.json
01-03 20:32:28.540 12935-12935/? D/com.pbm: TIMING ENDING REGION
01-03 20:32:28.545 1500-4700/? I/ActivityManager: START u0 {cmp=com.pbm/.PBMMenu} from uid 10103 on display 0
01-03 20:32:28.556 12935-13007/? D/com.pbm: TIMING STARTING MACHINES
01-03 20:32:28.557 12935-13008/? D/com.pbm: TIMING STARTING LOCATION, LOCATION TYPES, OPERATORS
01-03 20:32:28.559 12935-13009/? D/com.pbm: TIMING STARTING ZONES
01-03 20:32:28.568 12935-12935/? I/Choreographer: Skipped 141 frames!  The application may be doing too much work on its main thread.
01-03 20:32:28.638 4807-5813/? D/SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
01-03 20:32:28.639 4807-5813/? D/GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=10240000, packageName='com.pbm', extras=Bundle[{client_name=locationServices}]}
01-03 20:32:28.668 12935-12935/? D/com.pbm.location: PBM onConnected
01-03 20:32:28.669 4807-28346/? D/GmsLocManagerSvcImpl: getLastLocationWithPackage: com.pbm
01-03 20:32:28.678 4807-21529/? D/GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=false, triggerUpdate=false, clients=[], tag='null', hideFromAppOps=false, forceCoarseLocation=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@3a93738, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@b2fc311}
01-03 20:32:28.679 4807-21529/? D/GmsLocProviderReal: network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-03 20:32:28.679 4807-21529/? D/GmsLocProviderReal: network: requesting location updates. minTime=3600000 minDistance=0.0
01-03 20:32:28.733 15490-15507/? D/IchnaeaBackendService: Cells: 1
01-03 20:32:28.736 15490-13031/? W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
01-03 20:32:28.737 15490-13031/? D/IchnaeaBackendService: request: {"radioType":"lte","cellTowers":[{"radioType":"lte","mobileCountryCode":310,"mobileNetworkCode":260,"locationAreaCode":15182,"cellId":20529410,"signalStrength":-114,"psc":391,"asu":26}],"wifiAccessPoints":[{"macAddress":"c4:01:7c:93:c2:b8","channel":3,"frequency":2422,"signalStrength":-79},{"macAddress":"0a:80:ae:a6:6b:1b","channel":11,"frequency":2462,"signalStrength":-88},{"macAddress":"a0:8e:78:58:71:72","channel":6,"frequency":2437,"signalStrength":-86},{"macAddress":"24:79:2a:54:4c:c3","channel":6,"frequency":2437,"signalStrength":-80},{"macAddress":"84:16:f9:25:42:38","channel":3,"frequency":2422,"signalStrength":-78},{"macAddress":"c4:01:7c:96:fd:18","channel":7,"frequency":2442,"signalStrength":-77},{"macAddress":"8c:0c:90:bc:e8:d8","channel":11,"frequency":2462,"signalStrength":-73},{"macAddress":"58:ef:68:ac:4b:17","channel":3,"frequency":2422,"signalStrength":-85},{"macAddress":"c4:01:7c:d6:fd:18","channel":7,"frequency":2442,"signalStrength":-64},{"macAddress":"3c:36:e4:f3:1b:c0","channel":1,"frequency":2412,"signalStrength":-78},{"macAddress":"f8:18:97:51:7e:42","channel":6,"frequency":2437,"signalStrength":-77},{"macAddress":"70:3a:cb:53:d7:d2","channel":11,"frequency":2462,"signalStrength":-86},{"macAddress":"24:79:2a:13:ae:69","channel":3,"frequency":2422,"signalStrength":-86},{"macAddress":"a8:6b:ad:f8:2b:8a","channel":11,"frequency":2462,"signalStrength":-80},{"macAddress":"0e:02:8e:9e:b3:4f","channel":8,"frequency":2447,"signalStrength":-78},{"macAddress":"3c:36:e4:53:28:f0","channel":11,"frequency":2462,"signalStrength":-84},{"macAddress":"00:15:ff:d3:76:fc","channel":6,"frequency":2437,"signalStrength":-61},{"macAddress":"8c:0c:90:3c:e8:d8","channel":11,"frequency":2462,"signalStrength":-73},{"macAddress":"dc:45:17:0b:aa:70","channel":9,"frequency":2452,"signalStrength":-81},{"macAddress":"24:79:2a:93:ae:68","channel":3,"frequency":2422,"signalStrength":-85},{"macAddress":"c4:01:7c:16:fd:19","channel":7,"frequency":2442,"signalStrength":-77},{"macAddress":"c4:01:7c:56:fd:18","channel":7,"frequency":2442,"signalStrength":-78},{"macAddress":"8c:0c:90:fc:e8:d8","channel":11,"frequency":2462,"signalStrength":-75},{"macAddress":"24:79:2a:53:ae:68","channel":3,"frequency":2422,"signalStrength":-85},{"macAddress":"8c:0c:90:7c:e8:d8","channel":11,"frequency":2462,"signalStrength":-73},{"macAddress":"c4:01:7c:16:fd:18","channel":7,"frequency":2442,"signalStrength":-76},{"macAddress":"44:1c:a8:e1:17:ac","channel":1,"frequency":2412,"signalStrength":-76},{"macAddress":"00:30:44:18:e8:2e","channel":1,"frequency":2412,"signalStrength":-70},{"macAddress":"d4:04:cd:f3:e7:97","channel":11,"frequency":2462,"signalStrength":-86},{"macAddress":"d4:05:98:4d:09:f0","channel":11,"frequency":2462,"signalStrength":-80},{"macAddress":"38:4c:90:82:70:b0","channel":6,"frequency":2437,"signalStrength":-76},{"macAddress":"24:79:2a:d3:ae:68","channel":3,"frequency":2422,"signalStrength":-85}],"fallbacks":{"lacf":true,"ipf":false}}
01-03 20:32:28.741 1500-1796/? I/ActivityManager: Displayed com.pbm/.PBMMenu: +142ms (total +5s534ms)
01-03 20:32:29.071 12935-13010/? D/com.pbm: https://pinballmap.com/api/v1/machines.json?no_details=1;user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:29.936 15490-13031/? D/IchnaeaBackendService: response: {"location": {"lat": 34.1204957, "lng": -118.2281161}, "accuracy": 153.2758968}
01-03 20:32:29.944 4807-4807/? D/GmsLocRequestHelper: sending Location: Location[network 34.120496,-118.228116 acc=153 et=+2d10h24m10s92ms {Bundle[mParcelledData.dataSize=600]}]
01-03 20:32:29.947 12935-12935/? D/com.pbm.location: PBM onLocationChangedLocation[fused 34.120496,-118.228116 acc=153 et=+2d10h24m10s92ms {Bundle[mParcelledData.dataSize=600]}]
01-03 20:32:29.947 12935-12935/? D/com.pbm.location: PBM processLocation Location[fused 34.120496,-118.228116 acc=153 et=+2d10h24m10s92ms {Bundle[mParcelledData.dataSize=600]}]
01-03 20:32:30.751 12935-13010/? D/com.pbm: https://pinballmap.com/api/v1/region/la/locations.json?no_details=1;user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:31.015 12935-13010/? D/com.pbm: https://pinballmap.com/api/v1/region/la/zones.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:31.102 12935-13009/? D/com.pbm: TIMING ENDING ZONES
01-03 20:32:33.657 12935-12959/? D/com.pbm: https://pinballmap.com/api/v1/location_types.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:34.233 1500-11420/? I/ActivityManager: START u0 {cmp=com.pbm/.RecentlyAdded} from uid 10103 on display 0
01-03 20:32:34.245 4807-30906/? D/GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=2, request=null, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@2568ee4, pendingIntent=null, callback=null, fusedLocationProviderCallback=null}
01-03 20:32:34.245 4807-30906/? D/GmsLocProviderReal: gps: removeRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=Location[fused 34.120496,-118.228116 acc=153 et=+2d10h24m10s92ms {Bundle[mParcelledData.dataSize=600]}]}
01-03 20:32:34.246 4807-30906/? D/GmsLocProviderReal: network: removeRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=Location[fused 34.120496,-118.228116 acc=153 et=+2d10h24m10s92ms {Bundle[mParcelledData.dataSize=600]}]}
01-03 20:32:34.246 4807-30906/? D/GmsLocProviderReal: network: no longer requesting location update
01-03 20:32:34.283 12935-12935/? I/GAv4: Google Analytics 10.2.40 is starting up. To enable debug logging on a device run:
                                           adb shell setprop log.tag.GAv4 DEBUG
                                           adb logcat -s GAv4
01-03 20:32:34.298 12935-13055/? W/GAv4: AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
01-03 20:32:34.299 12935-12935/? D/com.pbm: ENABLING SPINNER
01-03 20:32:34.309 12935-13055/? W/GAv4: CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
01-03 20:32:34.320 12935-13055/? W/GAv4: AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
01-03 20:32:34.350 4807-18802/? D/SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
01-03 20:32:34.350 4807-18802/? D/GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=10240000, packageName='com.pbm', extras=Bundle[{client_name=locationServices}]}
01-03 20:32:34.377 12935-12935/? D/com.pbm.location: PBM onConnected
01-03 20:32:34.377 1500-1796/? I/ActivityManager: Displayed com.pbm/.RecentlyAdded: +127ms
01-03 20:32:34.377 4807-23959/? D/GmsLocManagerSvcImpl: getLastLocationWithPackage: com.pbm
01-03 20:32:34.383 4807-16191/? D/GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=false, triggerUpdate=false, clients=[], tag='null', hideFromAppOps=false, forceCoarseLocation=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@f99da02, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@47a9f13}
01-03 20:32:34.383 4807-16191/? D/GmsLocProviderReal: network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-03 20:32:34.383 4807-16191/? D/GmsLocProviderReal: network: requesting location updates. minTime=3600000 minDistance=0.0
01-03 20:32:34.410 12935-12979/? D/OpenGLRenderer: endAllActiveAnimators on 0xb2aa8900 (ListView) with handle 0x7bd4c620
01-03 20:32:34.949 12935-12982/? D/com.pbm: https://pinballmap.com/api/v1/region/la/location_machine_xrefs.json?limit=20;user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:35.200 12935-12982/? D/com.pbm: https://pinballmap.com/api/v1/region/la/operators.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:35.325 12935-12982/? D/com.pbm: https://pinballmap.com/api/v1/region/la/locations/6429.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:35.460 12935-13008/? D/com.pbm: TIMING ENDING LOCATION, LOCATION TYPES, OPERATORS
01-03 20:32:35.654 12935-13010/? D/com.pbm: https://pinballmap.com/api/v1/region/la/locations/8508.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:36.123 12935-12959/? D/com.pbm: https://pinballmap.com/api/v1/region/la/locations/1323.json?user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:37.226 12935-13057/? E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                   Process: com.pbm, PID: 12935
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'com.pbm.m com.pbm.k.a(android.app.Activity)' on a null object reference
                                                       at com.pbm.RecentlyAdded.b(Unknown Source)
                                                       at com.pbm.RecentlyAdded$1.run(Unknown Source)
                                                       at java.lang.Thread.run(Thread.java:761)
01-03 20:32:37.229 1500-4730/? W/ActivityManager:   Force finishing activity com.pbm/.RecentlyAdded
01-03 20:32:37.238 4807-4824/? D/GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=2, request=null, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@ddec349, pendingIntent=null, callback=null, fusedLocationProviderCallback=null}
01-03 20:32:37.238 4807-4824/? D/GmsLocProviderReal: gps: removeRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-03 20:32:37.239 4807-4824/? D/GmsLocProviderReal: network: removeRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-03 20:32:37.239 4807-4824/? D/GmsLocProviderReal: network: no longer requesting location update
01-03 20:32:37.239 1500-13111/? W/DropBoxManagerService: Dropping: data_app_crash (419 > 0 bytes)
01-03 20:32:37.299 1500-29323/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-03 20:32:37.299 1500-29323/? D/OpenGLRenderer: Swap behavior 1
01-03 20:32:37.323 4807-4826/? D/SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
01-03 20:32:37.323 4807-4826/? D/GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=10240000, packageName='com.pbm', extras=Bundle[{client_name=locationServices}]}
01-03 20:32:37.327 12935-12935/? D/com.pbm.location: PBM onConnected
01-03 20:32:37.330 4807-5813/? D/GmsLocManagerSvcImpl: getLastLocationWithPackage: com.pbm
01-03 20:32:37.337 4807-5272/? D/GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=false, triggerUpdate=false, clients=[], tag='null', hideFromAppOps=false, forceCoarseLocation=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@be6196f, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@792d67c}
01-03 20:32:37.338 4807-5272/? D/GmsLocProviderReal: network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=102, interval=3600000, fastestInterval=60000, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
01-03 20:32:37.338 4807-5272/? D/GmsLocProviderReal: network: requesting location updates. minTime=3600000 minDistance=0.0
01-03 20:32:38.779 12935-12982/? D/com.pbm: https://pinballmap.com/api/v1/machines.json?no_details=1;region_id=5;user_email=gratzer@fastmail.com;user_token=xxx
01-03 20:32:38.850 12935-13007/? D/com.pbm: TIMING ENDING MACHINES
01-03 20:32:38.851 12935-13006/? D/com.pbm: ALL DONE
````

**Comment by scottwainstock** [comment]
@RyanTG Would you mind doing this again, but having it start FROM Android Studio? It'll ask you to replace the app on your phone... just do that. Notice how the NullPointerException part has "Unknown Source" and no line numbers and all that? It's proguard obfuscating the logs. If you run it all from Android Studio, we'll get line numbers / etc.

**Comment by RyanTG** [comment]
Replaced log and pasted it here: https://gist.github.com/RyanTG/2d2635418e2b098c18648495bc441586

**Comment by scottwainstock** [comment]
@RyanTG How about this?

https://github.com/scottwainstock/pbm-android/commit/3633f63851f7e6b2238258f9343fe9eff62402cf

**Comment by RyanTG** [comment]
Did not crash. Took quite a while to load, though. See gist https://gist.github.com/RyanTG/18f99ebff499e30cbd8d45d795c920b7

**Comment by scottwainstock** [comment]
Yeah it has to get detail info on 20 locations/machines... that's part of
the "lazy loading" thing. We could work on caching that so it doesn't do
the load every single time I guess.

**Comment by RyanTG** [comment]
Well, since that's a separate task, maybe this is good to ship then. Should I test anything else?

**Comment by scottwainstock** [comment]
@RyanTG I don't think so.. but given our issue last week, I put a signed build here:
scottwainstock.com/app-release.apk

I'm checking it on my Nexus... maybe check it real quick on your phone?

**Comment by RyanTG** [comment]
Checking

**Comment by RyanTG** [comment]
Crap! The issue also exists on Recent High Scores.

I should have realized that earlier.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm-android/commit/8d7d3d81b5c4c0fc2da16f10890e77b738efd760

**Comment by scottwainstock** [comment]
@RyanTG I'm going to bed... but if you like that, I can put a build out tomorrow after work.

**Comment by RyanTG** [comment]
Seems good!
